######################## default configuration ####################
baseURL = "/"
title = "Twenty Twenty Hugo"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
pagination.pagerSize = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45


[services.disqus]
shortname = 'themefisher-template' # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/

############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]
