baseURL = "https://hugo-daanasma.netlify.app/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Daan Asma"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "The New UMoMA Opens its Doors"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = "123 Main Street <br> New York, NY 10001"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
